### ISSUE TITLE
[BUG] Checkout function deducted product count to negative integer

### ISSUE THREAD

**Issue by whongam** [NY1105/e-commerce#6]
## Summary
During checkout (/checkout), the inventory count is deducted to negative numbers.

## Severity

Major

## Reporter

@whongam
## Assignee

@NY1105

## Component

Backend API -> cart

## Version

Release 2

## Environment

Visual Studio Code

> Version: 1.85.0 (Universal)  
> Commit: af28b32d7e553898b2a91af498b1fb666fdebe0c  
> Date: 2023-12-06T18:18:04.614Z (4 days ago)  
> Electron: 25.9.7  
> ElectronBuildId: 25551756  
> Chromium: 114.0.5735.289  
> Node.js: 18.15.0  
> V8: 11.4.183.29-electron.0  
> OS: macOS Darwin arm64 22.6.0

Thunder Client (Equivalent to Postman)

> v2.16.2

## Description

1.  Prerequisites:  
    1.0 Make sure the database is initiated  
    1.1 In CLI, run  `mvn spring-boot:run`  to start the server
2.  In API caller, request  
	`POST localhost:8080/cart/checkout/?cartId=0`  with body:  
    `{ "userId": "user123", "userPassword": "pass456" }`

## Current result
	 cart.getProducts()
` {cartId: 0 , {productId:0, price: 10.0, inventory: 0}}`

## Actual
	cart.getProducts()
` {cartId: 0 , {productId:0, price: 10.0, inventory: -1}}`

**Comment by NY1105** [comment]
## Problem
Missing condition of checking inventory count

## Solution
Added condition to check if inventory is available
```
    public double checkout(Long cartId, User user) {
      Optional<User> authed_user = user_service.auth(user);
      
      if (authed_user.isEmpty())
        return -1;
      Optional<Cart> cart = cart_repository.findById(cartId);
      if (cart.isEmpty())
        return 0;
      double total = getDiscountedTotalPrice(cart.get(), authed_user.get());
      product_service.adjustInventory(cart.get());
      if (!isInventoryAvailable(cart.get())) {
        return -1; // or any other error code to indicate insufficient inventory
      }
      authed_user.get().setTotalSpent(authed_user.get().getTotalSpent()+total);
      user_repository.saveAndFlush(authed_user.get());
      return total;
    }

    private boolean isInventoryAvailable(Cart cart) {
      for (Product product : cart.getProducts()) {
        if (product.getInventory() < 0) {
          return false;
        }
      }
      return true;
    }
```

## Conclusion
Fixed, Tested, Closing
