### ISSUE TITLE
Checkout Output Is Not JSON formatted

### ISSUE THREAD

**Issue by WongSinYan** [NY1105/e-commerce#7]
## Summary
The output of checkout is not JSON format

## Severity
Minor

## Reporter
@wsy617

## Assignee
@NY1105 

## Product
e-commerce

## Component
Cart

## Version
Release 2

## Environment
Visual Studio Code 
> Version: 1.85.0 (Universal)
> Commit: af28b32d7e553898b2a91af498b1fb666fdebe0c
> Date: 2023-12-06T18:18:04.614Z (4 days ago)
> Electron: 25.9.7
> ElectronBuildId: 25551756
> Chromium: 114.0.5735.289
> Node.js: 18.15.0
> V8: 11.4.183.29-electron.0
> OS: macOS Darwin arm64 22.6.0

Thunder Client (Equivalent to Postman)
> v2.16.2

**Comment by NY1105** [comment]
## Problem
Did not format String as JSON

## Solution
Linting
![WhatsApp Image 2023-12-11 at 22 21 10](https://github.com/NY1105/e-commerce/assets/106720483/6fbb3087-a4cb-4aa7-80fa-dcfd9977a2e4)

## Conclusion
Fixed, tested, closing
